# Generated by Django 3.1.5 on 2021-03-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='minted',
            field=models.TextField(default='[]', verbose_name='minted tokens'),
        ),
    ]
