# Generated by Django 3.1.5 on 2021-03-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='uuid',
            new_name='token',
        ),
    ]
