# Generated by Django 3.1.5 on 2021-03-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_auto_20210328_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='owner',
            field=models.CharField(default='charles', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
