# Generated by Django 3.1.5 on 2021-03-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_token_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='owner',
            field=models.CharField(max_length=20),
        ),
    ]
