# Generated by Django 3.1.5 on 2021-03-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_auto_20210328_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='category',
            field=models.CharField(choices=[('ART', 'Art'), ('MUS', 'Music'), ('ETC', 'Other')], default='charles', max_length=3),
            preserve_default=False,
        ),
    ]
