# Generated by Django 3.1.5 on 2021-03-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_token_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='time_end',
        ),
        migrations.AddField(
            model_name='auction',
            name='n_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
