# Generated by Django 3.1.5 on 2021-03-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0007_auto_20210328_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
