# Generated by Django 3.1.5 on 2021-03-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0009_auto_20210328_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winning',
            field=models.CharField(default='charles', max_length=20),
            preserve_default=False,
        ),
    ]
